
#ifndef RESOURCES_HPP_INCLUDED
#define RESOURCES_HPP_INCLUDED

#define __ARTIRELLY_SIZE_X 50
#define __ARTIRELLY_SIZE_Y 12
#define __ARTIRELLY_POWER_MIN 10
#define __ARTIRELLY_BARREL_LENGTH 15

#define __IDC__USER 100

#define __IDC__GROUND (__IDC__USER + 1)
#define __IDC__TOOLBAR (__IDC__USER + 2)
#define __IDC__TOOLBAR__BUTTON__NEW_GAME (__IDC__USER + 3)
#define __IDC__TOOLBAR__BUTTON__FIRE (__IDC__USER + 4)
#define __IDC__TOOLBAR__BUTTON__PASS (__IDC__USER + 5)
#define __IDC__TOOLBAR__LABEL_ANGLE (__IDC__USER + 6)
#define __IDC__TOOLBAR__SPINBUTTON__ANGLE (__IDC__USER + 7)
#define __IDC__TOOLBAR__LABEL_POWER (__IDC__USER + 8)
#define __IDC__TOOLBAR__SPINBUTTON__POWER (__IDC__USER + 9)
#define __IDC__PLAYER1 (__IDC__USER + 10)
#define __IDC__PLAYER2 (__IDC__USER + 11)

#endif // RESOURCES_HPP_INCLUDED
