
#ifndef RESOURCES_HPP_INCLUDED
#define RESOURCES_HPP_INCLUDED

#define __ARTIRELLY_SIZE_X 50
#define __ARTIRELLY_SIZE_Y 12
#define __ARTIRELLY_POWER_MIN 10
#define __ARTIRELLY_BARREL_LENGTH 15

#define __IDC__GROUND 1
#define __IDC__TOOLBAR 2
#define __IDC__TOOLBAR__BUTTON__NEW_GAME 3
#define __IDC__PLAYER1 4
#define __IDC__PLAYER2 5

#endif // RESOURCES_HPP_INCLUDED
